version: "3.9"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID 
      API_HASH: $API_HASH 
      SESSION1: $SESSION1
      SESSION2: $SESSION2 
      SESSION3: $SESSION3
      SESSION4: $SESSION4
      SESSION5: $SESSION5
      SESSION6: $SESSION6 
      SESSION7: $SESSION7
      SESSION8: $SESSION8
      BOT_TOKEN: $BOT_TOKEN 
      SUDO_USERS: $SUDO_USERS 
      HNDLR: $HNDLR
